# Generated by Django 5.1.1 on 2024-09-19 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Não é possivel avaliar um filme com menos que 0 estrelas.'), django.core.validators.MaxValueValidator(5, 'Não é possivel avaliar um filme com mais que 5 estrelas.')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_movie', to='movies.movie')),
            ],
        ),
    ]
