# Generated by Django 5.1.1 on 2024-09-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'ordering': ['name']},
        ),
    ]
